### ISSUE TITLE
Let user resolve dependency conflicts

### ISSUE THREAD

**Issue by accuminium** [fabianschuiki/bender#2]
Currently, bender reports an error when it encounters conflicting version requirements on a dependency. A common scenario where this happens is when I set the revision of a dependency to a feature branch to make a feature that is not yet released available early in development.

In this case, I would like to be able to resolve the conflict interactively and store my decision in the `Bender.lock` file.

The interaction could be as follows:
```
Requirement `^1.2.3` conflicts with other requirements on dependency `common_pkg`:
- package `my_pkg` requires `new_feature`
- package `other_pkg` requires `^1.2.3`

To resolve this conflict manually, select a revision for `common_pkg` among:
1) `1.2.3`
2) `new_feature`
Enter a number or hit enter to abort: 
```

If stdin is closed, bender should maintain its current behavior.

**Comment by fabianschuiki** [comment]
This has been completed as of 6ae2a71.
