### ISSUE TITLE
Vivado script has hardcoded path 

### ISSUE THREAD

**Issue by WRoenninger** [fabianschuiki/bender#22]
Should use $ROOT instead.

**Comment by fabianschuiki** [comment]
Excellent point, thanks! Do you feel like coding some Rust ;-) ? The relevant line is:

https://github.com/fabianschuiki/bender/blob/97f1b1332acb9e474fc11df51c56f9dd506154ad/src/cmd/script.rs#L508

This should look more like the one in the Synopsts command:

https://github.com/fabianschuiki/bender/blob/97f1b1332acb9e474fc11df51c56f9dd506154ad/src/cmd/script.rs#L364-L374

and

https://github.com/fabianschuiki/bender/blob/97f1b1332acb9e474fc11df51c56f9dd506154ad/src/cmd/script.rs#L434
