### ISSUE TITLE
sources not updated

### ISSUE THREAD

**Issue by msaideroglu** [fabianschuiki/bender#32]
![Screenshot from 2020-08-30 17-40-56](https://user-images.githubusercontent.com/23635889/91662140-180ce800-eae9-11ea-9fc4-0e728a04e3ef.png)
I tried to update sources of axi library. In shell window there was writing cloning, but it did not. Refer screenhot uploaded.

**Comment by fabianschuiki** [comment]
The `bender update` command re-resolves dependencies, but does not check out any files locally. Bender offers a couple of ways for you to use a library/package:
- `bender sources` can give you a raw list of files that you need to compile (try with `--help`)
- `bender script` can generate compile scripts for various EDA tools for you (vsim, vcs, verilator, etc.; try with `--help`)
Any of these commands will checkout the additional sources that are required for you.
