### ISSUE TITLE
Add version requirement information to bender parents command

### ISSUE THREAD

**Issue by meggiman** [fabianschuiki/bender#45]
For recursive bumping of dependencies, the `parents` command is already really useful. However, a flag I am really missing for this command is the option to print the (semantic) version requirements along with the parents. This would make it much easier to identify parent packages that need version bumping.

**Comment by accuminium** [comment]
Thanks for this feedback, @meggiman !

**Comment by micprog** [comment]
I started implementing this, however was unsure how to appropriately fetch the version requirement. Completing the following TODO
https://github.com/fabianschuiki/bender/blob/c02bb93806fdfe8d0e030cbe0592e01d3ce354dc/src/cmd/parents.rs#L38
and adding appropriate prints to the following command
https://github.com/fabianschuiki/bender/blob/c02bb93806fdfe8d0e030cbe0592e01d3ce354dc/src/cmd/parents.rs#L49-L51
should fix this issue.
